=== RUN   TestIteration1
    iteration1_test.go:50: Не удалось дождаться пока порт 8080 станет доступен для запроса: context deadline exceeded
=== RUN   TestIteration1/TestCounterHandlers
=== RUN   TestIteration1/TestCounterHandlers/update
    iteration1_test.go:150: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:150
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:153: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:153
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/update
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/testCounter/100'
    iteration1_test.go:158: Оригинальный запрос:
        
        POST /update/counter/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestCounterHandlers/without_id
    iteration1_test.go:166: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:166
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/without_id
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:169: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:169
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/without_id
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/'
    iteration1_test.go:174: Оригинальный запрос:
        
        POST /update/counter/ HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestCounterHandlers/invalid_value
    iteration1_test.go:182: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:182
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/counter/testCounter/none": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestCounterHandlers/invalid_value
        	Messages:   	Ошибка при попытке сделать запрос с обновлением counter
    iteration1_test.go:185: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:185
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 0
        	Test:       	TestIteration1/TestCounterHandlers/invalid_value
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/counter/testCounter/none'
    iteration1_test.go:190: Оригинальный запрос:
        
        POST /update/counter/testCounter/none HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers
=== RUN   TestIteration1/TestGaugeHandlers/update
    iteration1_test.go:98: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:98
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testGauge/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:101: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:101
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/update
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testGauge/100'
    iteration1_test.go:106: Оригинальный запрос:
        
        POST /update/gauge/testGauge/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers/without_id
    iteration1_test.go:114: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:114
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/without_id
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:117: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:117
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/without_id
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/'
    iteration1_test.go:122: Оригинальный запрос:
        
        POST /update/gauge/ HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestGaugeHandlers/invalid_value
    iteration1_test.go:130: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:130
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testGauge/none": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestGaugeHandlers/invalid_value
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration1_test.go:133: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:133
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 400
        	            	actual  : 0
        	Test:       	TestIteration1/TestGaugeHandlers/invalid_value
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testGauge/none'
    iteration1_test.go:138: Оригинальный запрос:
        
        POST /update/gauge/testGauge/none HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestUnknownHandlers
=== RUN   TestIteration1/TestUnknownHandlers/update_invalid_type
    iteration1_test.go:202: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:202
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/unknown/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_type
        	Messages:   	Ошибка при попытке сделать запрос с не корректным типом метрики
    iteration1_test.go:205: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:205
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	[]int{400, 501} does not contain 0
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_type
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/unknown/testCounter/100'
    iteration1_test.go:210: Оригинальный запрос:
        
        POST /update/unknown/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration1/TestUnknownHandlers/update_invalid_method
    iteration1_test.go:218: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:218
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/updater/counter/testCounter/100": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_method
        	Messages:   	Ошибка при попытке сделать запрос с не корректным типом метрики
    iteration1_test.go:221: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration1_test.go:221
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	[]int{400, 404} does not contain 0
        	Test:       	TestIteration1/TestUnknownHandlers/update_invalid_method
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/updater/counter/testCounter/100'
    iteration1_test.go:226: Оригинальный запрос:
        
        POST /updater/counter/testCounter/100 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== NAME  TestIteration1
    iteration1_test.go:70: Процесс завершился с не нулевым статусом 2
    iteration1_test.go:82: Получен STDOUT лог процесса:
        
        cmd/server/server flag redefined: a
        panic: cmd/server/server flag redefined: a
        
        goroutine 1 [running]:
        flag.(*FlagSet).Var(0x1400006e180, {0x104ede098, 0x14000078120}, {0x104dd8667, 0x1}, {0x104dda368, 0xa})
        	/usr/local/go/src/flag/flag.go:982 +0x2a4
        flag.StringVar(...)
        	/usr/local/go/src/flag/flag.go:853
        github.com/NikitaBarysh/metrics_and_alertinc/internal/config/serverConfig.ParseServerConfig()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/internal/config/serverConfig/config.go:53 +0x1dc
        main.main()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/cmd/server/main.go:17 +0x20
--- FAIL: TestIteration1 (20.04s)
    --- FAIL: TestIteration1/TestCounterHandlers (0.03s)
        --- FAIL: TestIteration1/TestCounterHandlers/update (0.03s)
        --- FAIL: TestIteration1/TestCounterHandlers/without_id (0.00s)
        --- FAIL: TestIteration1/TestCounterHandlers/invalid_value (0.00s)
    --- FAIL: TestIteration1/TestGaugeHandlers (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/update (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/without_id (0.00s)
        --- FAIL: TestIteration1/TestGaugeHandlers/invalid_value (0.00s)
    --- FAIL: TestIteration1/TestUnknownHandlers (0.00s)
        --- FAIL: TestIteration1/TestUnknownHandlers/update_invalid_type (0.00s)
        --- FAIL: TestIteration1/TestUnknownHandlers/update_invalid_method (0.00s)
=== RUN   TestIteration2A
=== RUN   TestIteration2A/TestAgent
=== RUN   TestIteration2A/TestAgent/receive_data_from_agent
=== NAME  TestIteration2A
    iteration2a_test.go:80: Получен STDOUT лог процесса:
        
        Post "http://localhost:8080/update/gauge/NumForcedGC/0.00": read tcp [::1]:58192->[::1]:8080: read: connection reset by peer
        Post "http://localhost:8080/update/gauge/NumGC/0.00": dial tcp [::1]:8080: connect: connection refused
        interrupt
--- PASS: TestIteration2A (10.04s)
    --- PASS: TestIteration2A/TestAgent (0.00s)
        --- PASS: TestIteration2A/TestAgent/receive_data_from_agent (0.00s)
=== RUN   TestIteration2B
=== RUN   TestIteration2B/TestFilesPresence
=== RUN   TestIteration2B/TestServerCoverage
    iteration2b_test.go:87: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration2b_test.go:87
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestIteration2B/TestServerCoverage
        	Messages:   	Невозможно получить результат выполнения команды: /usr/local/go/bin/go test -cover ./.... Вывод:
        	            	
        	            	 # github.com/NikitaBarysh/metrics_and_alertinc/internal/storage/repositories
        	            	internal/storage/repositories/repository.go:74:38: fmt.Sprintf format %2f has arg metricValue.Delta of wrong type int64
        	            	internal/storage/repositories/repository.go:76:38: fmt.Sprintf format %d has arg metricValue.Value of wrong type float64
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/cmd/agent	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/cmd/server	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/config/agentConfig	[no test files]
        	            	?   	github.com/NikitaBarysh/metrics_and_alertinc/internal/config/serverConfig	[no test files]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/compress	(cached)	coverage: 0.0% of statements [no tests to run]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/handlers	(cached)	coverage: 45.6% of statements
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/logger	(cached)	coverage: 0.0% of statements [no tests to run]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/models	(cached)	coverage: 0.0% of statements [no tests to run]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/router	(cached)	coverage: 0.0% of statements [no tests to run]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/sender	(cached)	coverage: 0.0% of statements [no tests to run]
        	            	ok  	github.com/NikitaBarysh/metrics_and_alertinc/internal/storage	(cached)	coverage: 4.0% of statements
        	            	FAIL
--- FAIL: TestIteration2B (0.89s)
    --- PASS: TestIteration2B/TestFilesPresence (0.00s)
    --- FAIL: TestIteration2B/TestServerCoverage (0.88s)
=== RUN   TestIteration3A
=== RUN   TestIteration3A/TestFrameworkUsage
--- PASS: TestIteration3A (0.00s)
    --- PASS: TestIteration3A/TestFrameworkUsage (0.00s)
=== RUN   TestIteration3B
    iteration3b_test.go:53: Не удалось дождаться пока порт 8080 станет доступен для запроса: context deadline exceeded
=== RUN   TestIteration3B/TestCounter
=== RUN   TestIteration3B/TestCounter/update_sequence
    iteration3b_test.go:157: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:157
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/counter/testSetGet18": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestCounter/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос для получения значения counter
    iteration3b_test.go:162: Оригинальный запрос:
        
        GET /value/counter/testSetGet18 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration3B/TestCounter/get_unknown
    iteration3b_test.go:203: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:203
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/counter/testUnknown119": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestCounter/get_unknown
        	Messages:   	Ошибка при попытке сделать запрос для получения значения counter
    iteration3b_test.go:204: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:204
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration3B/TestCounter/get_unknown
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'GET http://localhost:8080/value/counter/testUnknown119'
    iteration3b_test.go:209: Оригинальный запрос:
        
        GET /value/counter/testUnknown119 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration3B/TestGauge
=== RUN   TestIteration3B/TestGauge/update_sequence
    iteration3b_test.go:103: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:103
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testSetGet90/760981.624": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration3b_test.go:106: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:106
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testSetGet90/760981.624'
    iteration3b_test.go:111: Оригинальный запрос:
        
        POST /update/gauge/testSetGet90/760981.624 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration3b_test.go:115: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:115
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/gauge/testSetGet90": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос для получения значения gauge
    iteration3b_test.go:117: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:117
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:119: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:119
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: "760981.624"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-760981.624
        	            	+
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие отправленного значения gauge (760981.624) полученному от сервера (), 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:124: Оригинальный запрос:
        
        GET /value/gauge/testSetGet90 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration3b_test.go:103: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:103
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testSetGet90/486888.172": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration3b_test.go:106: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:106
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testSetGet90/486888.172'
    iteration3b_test.go:111: Оригинальный запрос:
        
        POST /update/gauge/testSetGet90/486888.172 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration3b_test.go:115: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:115
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/gauge/testSetGet90": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос для получения значения gauge
    iteration3b_test.go:117: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:117
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:119: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:119
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: "486888.172"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-486888.172
        	            	+
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие отправленного значения gauge (486888.172) полученному от сервера (), 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:124: Оригинальный запрос:
        
        GET /value/gauge/testSetGet90 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration3b_test.go:103: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:103
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/gauge/testSetGet90/226578.357": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration3b_test.go:106: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:106
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'POST http://localhost:8080/update/gauge/testSetGet90/226578.357'
    iteration3b_test.go:111: Оригинальный запрос:
        
        POST /update/gauge/testSetGet90/226578.357 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration3b_test.go:115: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:115
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/gauge/testSetGet90": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Ошибка при попытке сделать запрос для получения значения gauge
    iteration3b_test.go:117: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:117
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:119: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:119
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: "226578.357"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-226578.357
        	            	+
        	Test:       	TestIteration3B/TestGauge/update_sequence
        	Messages:   	Несоответствие отправленного значения gauge (226578.357) полученному от сервера (), 'GET http://localhost:8080/value/gauge/testSetGet90'
    iteration3b_test.go:124: Оригинальный запрос:
        
        GET /value/gauge/testSetGet90 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== RUN   TestIteration3B/TestGauge/get_unknown
    iteration3b_test.go:133: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:133
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Get "http://localhost:8080/value/gauge/testUnknown247": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration3B/TestGauge/get_unknown
        	Messages:   	Ошибка при попытке сделать запрос для получения значения gauge
    iteration3b_test.go:135: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration3b_test.go:135
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Not equal: 
        	            	expected: 404
        	            	actual  : 0
        	Test:       	TestIteration3B/TestGauge/get_unknown
        	Messages:   	Несоответствие статус кода ответа ожидаемому в хендлере 'GET http://localhost:8080/value/gauge/testUnknown247'
    iteration3b_test.go:140: Оригинальный запрос:
        
        GET /value/gauge/testUnknown247 HTTP/1.1
        Host: localhost:8080
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
=== NAME  TestIteration3B
    iteration3b_test.go:73: Процесс завершился с не нулевым статусом 2
    iteration3b_test.go:85: Получен STDOUT лог процесса:
        
        cmd/server/server flag redefined: a
        panic: cmd/server/server flag redefined: a
        
        goroutine 1 [running]:
        flag.(*FlagSet).Var(0x1400006e180, {0x102f5a098, 0x14000078120}, {0x102e54667, 0x1}, {0x102e56368, 0xa})
        	/usr/local/go/src/flag/flag.go:982 +0x2a4
        flag.StringVar(...)
        	/usr/local/go/src/flag/flag.go:853
        github.com/NikitaBarysh/metrics_and_alertinc/internal/config/serverConfig.ParseServerConfig()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/internal/config/serverConfig/config.go:53 +0x1dc
        main.main()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/cmd/server/main.go:17 +0x20
--- FAIL: TestIteration3B (20.02s)
    --- FAIL: TestIteration3B/TestCounter (0.01s)
        --- FAIL: TestIteration3B/TestCounter/update_sequence (0.00s)
        --- FAIL: TestIteration3B/TestCounter/get_unknown (0.00s)
    --- FAIL: TestIteration3B/TestGauge (0.01s)
        --- FAIL: TestIteration3B/TestGauge/update_sequence (0.01s)
        --- FAIL: TestIteration3B/TestGauge/get_unknown (0.00s)
=== RUN   TestIteration4
    iteration4_test.go:38: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration4_test.go:38
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:37
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration4
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration4 (0.00s)
=== RUN   TestIteration5
    iteration5_test.go:33: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration5_test.go:33
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:41
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration5
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration5 (0.00s)
=== RUN   TestIteration6
=== RUN   TestIteration6/TestLoggerUsage
--- PASS: TestIteration6 (0.00s)
    --- PASS: TestIteration6/TestLoggerUsage (0.00s)
=== RUN   TestIteration7
    iteration7_test.go:76: Не удалось дождаться пока порт 8080 станет доступен для запроса: context deadline exceeded
=== RUN   TestIteration7/TestCollectAgentMetrics
    iteration7_test.go:395: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration7_test.go:395
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/value/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration7/TestCollectAgentMetrics
        	Messages:   	Ошибка при попытке сделать запрос с получением значения PollCount
    iteration7_test.go:421: Оригинальный запрос:
        
        POST /value/ HTTP/1.1
        Host: localhost:8080
        Accept: application/json
        Content-Type: application/json
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration7_test.go:423: Оригинальный ответ:
        
=== RUN   TestIteration7/TestCounterHandlers
=== RUN   TestIteration7/TestCounterHandlers/update
    iteration7_test.go:199: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration7_test.go:199
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/value/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration7/TestCounterHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с получением значения counter
    iteration7_test.go:214: Несоответствие статус кода 0 ответа ожидаемому http.StatusNotFound или http.StatusOK в хендлере "POST": "http://localhost:8080/value/"
=== RUN   TestIteration7/TestEncoderUsage
=== RUN   TestIteration7/TestGaugeHandlers
=== RUN   TestIteration7/TestGaugeHandlers/update
    iteration7_test.go:287: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration7_test.go:287
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:91
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:8080/update/": dial tcp [::1]:8080: connect: connection refused
        	Test:       	TestIteration7/TestGaugeHandlers/update
        	Messages:   	Ошибка при попытке сделать запрос с обновлением gauge
    iteration7_test.go:314: Оригинальный запрос:
        
        POST /value/ HTTP/1.1
        Host: localhost:8080
        Accept: application/json
        Content-Type: application/json
        User-Agent: go-resty/2.7.0 (https://github.com/go-resty/resty)
        
    iteration7_test.go:316: Оригинальный ответ:
        
=== NAME  TestIteration7
    iteration7_test.go:162: Получен STDOUT лог процесса:
        
        Post "http://localhost:8080/update/gauge/LastGC/0.00": read tcp [::1]:58643->[::1]:8080: read: connection reset by peer
        Post "http://localhost:8080/update/gauge/Alloc/172088.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapAlloc/172088.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/GCSys/2806160.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapInuse/786432.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/OtherSys/732667.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapIdle/3080192.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Mallocs/657.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/StackInuse/327680.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/counter/PollCount/5": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/GCCPUFraction/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapReleased/3014656.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Lookups/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/PauseTotalNs/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Sys/7801872.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/RandomValue/0.85": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Frees/10.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/StackSys/327680.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapObjects/647.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MCacheInuse/9600.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NextGC/4194304.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NumForcedGC/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/BuckHashSys/4181.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapSys/3866624.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MCacheSys/15600.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MSpanInuse/33760.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MSpanSys/48960.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NumGC/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/TotalAlloc/172088.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/GCSys/2874008.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapInuse/1122304.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/OtherSys/926963.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapIdle/2678784.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Mallocs/4239.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/StackInuse/393216.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/counter/PollCount/10": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/RandomValue/0.21": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/GCCPUFraction/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapReleased/2613248.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Lookups/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/PauseTotalNs/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Sys/8064016.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Frees/158.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/StackSys/393216.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapObjects/4081.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MCacheInuse/9600.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NextGC/4194304.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NumForcedGC/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/NumGC/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/TotalAlloc/412712.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/BuckHashSys/4181.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapSys/3801088.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MCacheSys/15600.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MSpanInuse/33760.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/MSpanSys/48960.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/LastGC/0.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/Alloc/412712.00": dial tcp [::1]:8080: connect: connection refused
        Post "http://localhost:8080/update/gauge/HeapAlloc/412712.00": dial tcp [::1]:8080: connect: connection refused
        interrupt
    iteration7_test.go:119: Процесс завершился с не нулевым статусом 2
    iteration7_test.go:131: Получен STDOUT лог процесса:
        
        cmd/server/server flag redefined: a
        panic: cmd/server/server flag redefined: a
        
        goroutine 1 [running]:
        flag.(*FlagSet).Var(0x1400012c120, {0x100816098, 0x14000100120}, {0x100710667, 0x1}, {0x100712368, 0xa})
        	/usr/local/go/src/flag/flag.go:982 +0x2a4
        flag.StringVar(...)
        	/usr/local/go/src/flag/flag.go:853
        github.com/NikitaBarysh/metrics_and_alertinc/internal/config/serverConfig.ParseServerConfig()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/internal/config/serverConfig/config.go:53 +0x1dc
        main.main()
        	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/cmd/server/main.go:17 +0x20
--- FAIL: TestIteration7 (20.12s)
    --- FAIL: TestIteration7/TestCollectAgentMetrics (0.11s)
    --- FAIL: TestIteration7/TestCounterHandlers (0.00s)
        --- FAIL: TestIteration7/TestCounterHandlers/update (0.00s)
    --- PASS: TestIteration7/TestEncoderUsage (0.01s)
    --- FAIL: TestIteration7/TestGaugeHandlers (0.00s)
        --- FAIL: TestIteration7/TestGaugeHandlers/update (0.00s)
=== RUN   TestIteration8
    iteration8_test.go:36: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration8_test.go:36
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:53
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration8
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration8 (0.00s)
=== RUN   TestIteration9
    iteration9_test.go:36: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration9_test.go:36
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:57
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration9
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration9 (0.00s)
=== RUN   TestIteration10A
    iteration10a_test.go:33: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration10a_test.go:33
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:61
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration10A
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration10A (0.00s)
=== RUN   TestIteration10B
    iteration10b_test.go:32: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration10b_test.go:32
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:65
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration10B
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration10B (0.00s)
=== RUN   TestIteration11
    iteration11_test.go:40: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration11_test.go:40
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:69
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration11
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration11 (0.00s)
=== RUN   TestIteration12
    iteration12_test.go:39: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration12_test.go:39
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:73
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration12
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration12 (0.00s)
=== RUN   TestIteration13
    iteration13_test.go:35: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration13_test.go:35
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:77
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration13
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration13 (0.00s)
=== RUN   TestIteration14
    iteration14_test.go:38: 
        	Error Trace:	/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/iteration14_test.go:38
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/suite.go:132
        	            				/Users/nikitabar/Dev/test_metric/metrics_and_alertinc/main_test.go:81
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestIteration14
        	Messages:   	-server-port non-empty flag required
--- FAIL: TestIteration14 (0.00s)
FAIL
